/**
 * Website configuration — injected by the Scaffold Engine from truth-source/.
 * DO NOT EDIT MANUALLY — regenerated by `pnpm scaffold`.
 * Last scaffolded: 2026-05-28T13:23:12.221Z
 */

/** @type {import('../../../src/shared/types').WebsiteConfig} */
export default {
  // ── NAP (Name · Address · Phone) ─────────────────────────────────────────
  businessName:   "Jax Roofing",
  phone:          "3176275668",
  address:        "1438 East Raymond",
  city:           "Indianapolis",
  state:          "IN",
  zip:            "46203",
  domain:         "[PLACEHOLDER: domain.com]" /* ← fill in before deploying */,

  // ── Brand ─────────────────────────────────────────────────────────────────
  primaryColor:   "[PLACEHOLDER: #HEX]" /* ← fill in before deploying */,
  secondaryColor: "[PLACEHOLDER: #HEX]" /* ← fill in before deploying */,

  // ── CTA routing ───────────────────────────────────────────────────────────
  //   call  → emergency funnel  (phone number is the primary CTA)
  //   form  → considered funnel (estimate form is the primary CTA)
  //   dual  → both funnels active; emergency phone is the dominant CTA
  primaryCtaType:  "dual",
  primaryCtaValue: "3176275668",
  formEndpoint:    "[PLACEHOLDER: https://jaxroofing.com/estimate]" /* ← fill in before deploying */,

  // ── Analytics ─────────────────────────────────────────────────────────────
  gtmId:          "[GTM_ID]" /* ← fill in before deploying */,
};
