/**
 * AGENCY-OS SCAFFOLD ENGINE
 *
 * Injects truth-source data into each client's template files.
 * Runs automatically before the deployment-validator via the prebuild hook.
 *
 * Writes (per client):
 *   website/config.js          — NAP + brand + CTA routing
 *   seo/local-citations.json   — NAP sync from truth-source
 *   leads/conversion-data.json — emergency phone sync from NAP
 *
 * Exit codes:
 *   0 — all clients scaffolded (warnings are logged but don't block)
 *   1 — fatal error (truth-source unreadable, file-write failure, etc.)
 *
 * Usage:
 *   tsx scripts/scaffold-engine.ts                        # all clients
 *   tsx scripts/scaffold-engine.ts --client jax-roofing  # one client only
 */

import fs   from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

// ── Constants ─────────────────────────────────────────────────────────────────

const ROOT        = path.resolve(import.meta.dirname, '..');
const CLIENTS_DIR = path.join(ROOT, 'clients');
const TS_DIR      = path.join(ROOT, 'truth-source');

// ── Terminal colours (no external deps) ──────────────────────────────────────

const c = {
  bold:   (s: string) => `\x1b[1m${s}\x1b[0m`,
  dim:    (s: string) => `\x1b[2m${s}\x1b[0m`,
  red:    (s: string) => `\x1b[31m${s}\x1b[0m`,
  green:  (s: string) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  cyan:   (s: string) => `\x1b[36m${s}\x1b[0m`,
};

// ── Types ─────────────────────────────────────────────────────────────────────

type PrimaryCtaType = 'call' | 'form' | 'dual';

interface InjectedConfig {
  businessName:    string;
  primaryColor:    string;
  secondaryColor:  string;
  phone:           string;
  address:         string;
  city:            string;
  state:           string;
  zip:             string;
  domain:          string;
  gtmId:           string;
  primaryCtaType:  PrimaryCtaType;
  primaryCtaValue: string;
  formEndpoint:    string;
}

interface ConversionData {
  funnel_type: string;
  emergency: {
    primary_action: string;
    phone:          string;
    cta_text:       string;
    response_time_promise?: string;
  };
  considered: {
    primary_action:      string;
    form_endpoint:       string;
    cta_text:            string;
    follow_up_sla_hours: number;
  };
  tracking?: {
    gtm_id?:               string;
    call_tracking_number?: string;
  };
}

interface ScaffoldResult {
  slug:     string;
  ok:       boolean;
  warnings: string[];
  errors:   string[];
  writes:   string[];
}

// ── Utilities ─────────────────────────────────────────────────────────────────

const PLACEHOLDER_RE = /^\[.+\]$/;

function isPlaceholder(val: unknown): boolean {
  return typeof val === 'string' && PLACEHOLDER_RE.test(val.trim());
}

function safeStr(val: unknown, fallback: string): string {
  if (typeof val !== 'string' || val.trim() === '') return fallback;
  return val.trim();
}

function safeNum(val: unknown, fallback: number): number {
  const n = Number(val);
  return Number.isFinite(n) ? n : fallback;
}

/** Write to .tmp then rename — disk is never partially written on error. */
function atomicWrite(targetPath: string, content: string): void {
  const tmpPath = `${targetPath}.tmp`;
  fs.writeFileSync(tmpPath, content, 'utf-8');
  fs.renameSync(tmpPath, targetPath);
}

/** Read a truth-source markdown file and return its raw frontmatter object. */
function readTsFrontmatter(filename: string): Record<string, unknown> {
  const fp = path.join(TS_DIR, filename);
  if (!fs.existsSync(fp)) throw new Error(`Truth-source file not found: ${fp}`);
  const { data } = matter(fs.readFileSync(fp, 'utf-8'));
  return data as Record<string, unknown>;
}

function obj(val: unknown): Record<string, unknown> {
  return (val !== null && typeof val === 'object' && !Array.isArray(val))
    ? (val as Record<string, unknown>)
    : {};
}

// ── config.js generator ───────────────────────────────────────────────────────

function generateConfigJs(v: InjectedConfig): string {
  // Annotate unfilled placeholders with inline comments so devs can spot them
  const jsStr = (val: string) =>
    isPlaceholder(val)
      ? `"${val}" /* ← fill in before deploying */`
      : JSON.stringify(val);

  return `/**
 * Website configuration — injected by the Scaffold Engine from truth-source/.
 * DO NOT EDIT MANUALLY — regenerated by \`pnpm scaffold\`.
 * Last scaffolded: ${new Date().toISOString()}
 */

/** @type {import('../../../src/shared/types').WebsiteConfig} */
export default {
  // ── NAP (Name · Address · Phone) ─────────────────────────────────────────
  businessName:   ${jsStr(v.businessName)},
  phone:          ${jsStr(v.phone)},
  address:        ${jsStr(v.address)},
  city:           ${jsStr(v.city)},
  state:          ${jsStr(v.state)},
  zip:            ${jsStr(v.zip)},
  domain:         ${jsStr(v.domain)},

  // ── Brand ─────────────────────────────────────────────────────────────────
  primaryColor:   ${jsStr(v.primaryColor)},
  secondaryColor: ${jsStr(v.secondaryColor)},

  // ── CTA routing ───────────────────────────────────────────────────────────
  //   call  → emergency funnel  (phone number is the primary CTA)
  //   form  → considered funnel (estimate form is the primary CTA)
  //   dual  → both funnels active; emergency phone is the dominant CTA
  primaryCtaType:  ${JSON.stringify(v.primaryCtaType)},
  primaryCtaValue: ${jsStr(v.primaryCtaValue)},
  formEndpoint:    ${jsStr(v.formEndpoint)},

  // ── Analytics ─────────────────────────────────────────────────────────────
  gtmId:          ${jsStr(v.gtmId)},
};
`;
}

// ── CTA routing resolver ──────────────────────────────────────────────────────

function resolveCta(
  conv: ConversionData,
  napPhone: string,
): { ctaType: PrimaryCtaType; ctaValue: string; formEndpoint: string } {
  // Prefer the NAP phone if the conversion-data phone is still a placeholder
  const livePhone = isPlaceholder(conv.emergency.phone) ? napPhone : conv.emergency.phone;
  const ft = conv.funnel_type.toLowerCase();

  if (ft === 'emergency') {
    return { ctaType: 'call', ctaValue: livePhone, formEndpoint: conv.considered.form_endpoint };
  }
  if (ft === 'considered') {
    return { ctaType: 'form',  ctaValue: conv.considered.form_endpoint, formEndpoint: conv.considered.form_endpoint };
  }
  // 'dual' or anything else → emergency phone is the dominant CTA
  return { ctaType: 'dual', ctaValue: livePhone, formEndpoint: conv.considered.form_endpoint };
}

// ── Per-client scaffold ───────────────────────────────────────────────────────

function scaffoldClient(
  slug:  string,
  brand: Record<string, unknown>,
  seo:   Record<string, unknown>,
  biz:   Record<string, unknown>,
): ScaffoldResult {
  const clientDir = path.join(CLIENTS_DIR, slug);
  const result: ScaffoldResult = { slug, ok: true, warnings: [], errors: [], writes: [] };

  // ── Extract NAP from truth-source/03-seo-and-aeo.md ──────────────────────
  const nap          = obj(seo['nap']);
  const businessName = safeStr(nap['business_name'],  '[PLACEHOLDER: Business Name]');
  const streetAddr   = safeStr(nap['street_address'], '[PLACEHOLDER: Street Address]');
  const city         = safeStr(nap['city'],           '[PLACEHOLDER: City]');
  const state        = safeStr(nap['state'],          '[PLACEHOLDER: State]');
  const zip          = safeStr(nap['zip'],            '[PLACEHOLDER: ZIP]');
  const phone        = safeStr(nap['phone'],          '[PLACEHOLDER: Phone]');

  for (const [field, val] of [
    ['business_name', businessName], ['phone', phone],
    ['street_address', streetAddr],  ['city', city],
    ['state', state],                ['zip', zip],
  ] as [string, string][]) {
    if (isPlaceholder(val)) {
      result.warnings.push(`nap.${field} is still a placeholder — fill in before deploying`);
    }
  }

  // ── Extract brand colours from truth-source/01-brand-identity.md ─────────
  const colors       = obj(brand['colors']);
  const primaryColor   = safeStr(colors['primary'],   '[PLACEHOLDER: #HEX]');
  const secondaryColor = safeStr(colors['secondary'], '[PLACEHOLDER: #HEX]');

  if (isPlaceholder(primaryColor))   result.warnings.push('colors.primary is still a placeholder');
  if (isPlaceholder(secondaryColor)) result.warnings.push('colors.secondary is still a placeholder');

  // ── Extract service radius from truth-source/02-business-operations.md ───
  const svcRadius  = obj(biz['service_radius']);
  const radiusMiles = safeNum(svcRadius['radius_miles'], 0);

  // ── Read leads/conversion-data.json ──────────────────────────────────────
  const leadsPath = path.join(clientDir, 'leads', 'conversion-data.json');
  let convData: ConversionData | null = null;

  if (!fs.existsSync(leadsPath)) {
    result.warnings.push('leads/conversion-data.json not found — defaulting to emergency/call funnel');
  } else {
    try {
      convData = JSON.parse(fs.readFileSync(leadsPath, 'utf-8')) as ConversionData;
    } catch (e) {
      result.warnings.push(`leads/conversion-data.json parse error: ${(e as Error).message} — defaulting to emergency/call funnel`);
    }
  }

  if (convData === null) {
    convData = {
      funnel_type: 'emergency',
      emergency:   { primary_action: 'call', phone, cta_text: 'Call Now' },
      considered:  { primary_action: 'form', form_endpoint: '[PLACEHOLDER: form URL]', cta_text: 'Get Estimate', follow_up_sla_hours: 24 },
    };
  }

  // ── Resolve CTA routing ───────────────────────────────────────────────────
  const { ctaType, ctaValue, formEndpoint } = resolveCta(convData, phone);

  // ── Preserve domain from existing config.js if already set ───────────────
  const configPath = path.join(clientDir, 'website', 'config.js');
  let domain = '[PLACEHOLDER: domain.com]';

  if (fs.existsSync(configPath)) {
    const existing = fs.readFileSync(configPath, 'utf-8');
    const m = /domain:\s*"([^"[\]]+)"/.exec(existing);
    if (m?.[1]) domain = m[1];
  }

  const gtmId = safeStr(convData.tracking?.gtm_id, '[GTM_ID]');

  const injected: InjectedConfig = {
    businessName, primaryColor, secondaryColor,
    phone, address: streetAddr, city, state, zip,
    domain, gtmId,
    primaryCtaType:  ctaType,
    primaryCtaValue: ctaValue,
    formEndpoint,
  };

  // ── Write 1: website/config.js ────────────────────────────────────────────
  const websiteDir = path.join(clientDir, 'website');
  if (!fs.existsSync(websiteDir)) {
    result.errors.push(`website/ directory not found for '${slug}'`);
    result.ok = false;
  } else {
    try {
      atomicWrite(configPath, generateConfigJs(injected));
      result.writes.push('website/config.js');
    } catch (e) {
      result.errors.push(`config.js write failed: ${(e as Error).message}`);
      result.ok = false;
    }
  }

  // ── Write 2: seo/local-citations.json (NAP sync) ─────────────────────────
  const citPath = path.join(clientDir, 'seo', 'local-citations.json');
  if (fs.existsSync(citPath)) {
    try {
      const existing = JSON.parse(fs.readFileSync(citPath, 'utf-8')) as Record<string, unknown>;
      const updated = {
        ...existing,
        business_name: businessName,
        address:       streetAddr,
        city,
        state,
        zip,
        phone,
        radius_miles:  radiusMiles > 0 ? radiusMiles : safeNum(existing['radius_miles'], 0),
      };
      atomicWrite(citPath, JSON.stringify(updated, null, 2) + '\n');
      result.writes.push('seo/local-citations.json');
    } catch (e) {
      result.errors.push(`local-citations.json sync failed: ${(e as Error).message}`);
      result.ok = false;
    }
  } else {
    result.warnings.push('seo/local-citations.json not found — skipping NAP sync');
  }

  // ── Write 3: leads/conversion-data.json (phone sync) ─────────────────────
  if (fs.existsSync(leadsPath)) {
    try {
      const livePhone = isPlaceholder(convData.emergency.phone) ? phone : convData.emergency.phone;
      const synced: ConversionData = {
        ...convData,
        emergency: { ...convData.emergency, phone: livePhone },
      };
      atomicWrite(leadsPath, JSON.stringify(synced, null, 2) + '\n');
      result.writes.push('leads/conversion-data.json');
    } catch (e) {
      result.errors.push(`conversion-data.json sync failed: ${(e as Error).message}`);
      result.ok = false;
    }
  }

  return result;
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main(): void {
  console.log(c.bold('\n╔══════════════════════════════════════════════════════╗'));
  console.log(c.bold('║       AGENCY-OS SCAFFOLD ENGINE                      ║'));
  console.log(c.bold('╚══════════════════════════════════════════════════════╝'));
  console.log(c.dim(`  ${new Date().toISOString()}\n`));

  // Optional --client <slug> arg
  const clientArgIdx  = process.argv.indexOf('--client');
  const targetClient  = clientArgIdx !== -1 ? process.argv[clientArgIdx + 1] : undefined;

  // ── Load truth-source ────────────────────────────────────────────────────
  let brand: Record<string, unknown>;
  let seo:   Record<string, unknown>;
  let biz:   Record<string, unknown>;

  try {
    brand = readTsFrontmatter('01-brand-identity.md');
    seo   = readTsFrontmatter('03-seo-and-aeo.md');
    biz   = readTsFrontmatter('02-business-operations.md');
  } catch (e) {
    console.error(c.red(`\n[FATAL] Cannot read truth-source: ${(e as Error).message}`));
    process.exit(1);
  }

  const napForLog = obj(seo['nap']);
  const logBiz    = safeStr(napForLog['business_name'], '(not set)');
  const logCity   = safeStr(napForLog['city'],          '(not set)');
  const logState  = safeStr(napForLog['state'],         '(not set)');

  console.log(c.green('  ✓  Truth-source loaded'));
  console.log(c.dim(`     NAP: ${logBiz} | ${logCity}, ${logState}\n`));

  // ── Discover clients ─────────────────────────────────────────────────────
  if (!fs.existsSync(CLIENTS_DIR)) {
    console.error(c.red('[FATAL] clients/ directory not found'));
    process.exit(1);
  }

  const allDirs     = fs.readdirSync(CLIENTS_DIR, { withFileTypes: true }).filter((d) => d.isDirectory());
  const templates   = allDirs.filter((d) =>  d.name.startsWith('[')).map((d) => d.name);
  const clientSlugs = allDirs.filter((d) => !d.name.startsWith('[')).map((d) => d.name);

  if (templates.length > 0) {
    console.log(c.dim(`  Skipping template director${templates.length === 1 ? 'y' : 'ies'}: ${templates.join(', ')}\n`));
  }

  if (targetClient !== undefined && !clientSlugs.includes(targetClient)) {
    console.error(c.red(`[FATAL] Client '${targetClient}' not found in clients/`));
    console.error(c.dim(`  Available: ${clientSlugs.length > 0 ? clientSlugs.join(', ') : '(none)'}`));
    process.exit(1);
  }

  const targets = targetClient !== undefined ? [targetClient] : clientSlugs;

  if (targets.length === 0) {
    console.log(c.yellow('  No client directories found. Nothing to scaffold.'));
    return;
  }

  console.log(c.cyan(`  Scaffolding ${targets.length} client(s): ${targets.join(', ')}\n`));

  // ── Scaffold each client ─────────────────────────────────────────────────
  const results: ScaffoldResult[] = [];

  for (const slug of targets) {
    console.log(c.bold(`  ▶  ${slug}`));
    const result = scaffoldClient(slug, brand, seo, biz);
    results.push(result);

    for (const w of result.writes) {
      console.log(c.green(`     ✓  ${w}`));
    }
    for (const warn of result.warnings) {
      console.log(c.yellow(`     ⚠  ${warn}`));
    }
    for (const err of result.errors) {
      console.log(c.red(`     ✗  ${err}`));
    }

    const badge = result.ok
      ? (result.warnings.length > 0 ? c.yellow('[WARN]') : c.green('[OK]'))
      : c.red('[FAILED]');
    console.log(`     Status: ${badge}\n`);
  }

  // ── Summary ──────────────────────────────────────────────────────────────
  const failCount = results.filter((r) => !r.ok).length;
  const warnCount = results.filter((r) => r.ok && r.warnings.length > 0).length;
  const cleanCount = results.filter((r) => r.ok && r.warnings.length === 0).length;

  console.log(c.bold('══════════════════════════════════════════════════════'));
  console.log(c.bold('  SUMMARY'));
  console.log(c.bold('══════════════════════════════════════════════════════'));
  console.log(`  Total  : ${c.bold(String(results.length))}`);
  console.log(`  ${c.green('OK')}     : ${cleanCount}`);
  console.log(`  ${c.yellow('Warned')} : ${warnCount}`);
  console.log(`  ${c.red('Failed')} : ${failCount}`);

  if (failCount > 0) {
    console.error(c.red(c.bold('\n  ✗  Scaffold failed for one or more clients.\n')));
    process.exit(1);
  }

  if (warnCount > 0) {
    console.log(c.yellow('\n  ⚠  Scaffold complete with warnings.'));
    console.log(c.yellow('     Placeholder values remain — run pnpm validate after filling them in.\n'));
  } else {
    console.log(c.green(c.bold('\n  ✓  All clients scaffolded successfully.\n')));
  }
}

main();
